name: Test and Build frontend app

defaults:
  run:
    working-directory: "backend/"

on:
  workflow_dispatch:
  push:
    branches:
    - backend

jobs:
  TestAndBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install 
      run: |
        apt-get update && apt-get -y install maven

    - name: Test
      run:
        mvn clean test

    - name: Build
      run:
        mvn clean package

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t ghcr.io/jonatasmonnerat/backend-app:1.0 .
        docker push ghcr.io/jonatasmonnerat/backend-app:1.0
